# Generated by Django 5.0.1 on 2024-02-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_message_updated_thread_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
    ]
